### ISSUE TITLE
feat: 이력서 / 면접 관련 부분 수정

### ISSUE THREAD

**Issue by SejeongMin** [UOS-TIK/tik-backend#17]
### TODO
- [x] 이력서 비활성화(soft delete) 구현
- [x] 면접 진행 suspend 함수 withContext 추가
- [x] techStack 조회 API
